routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ModeradorController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('comprasViviendas','ComprasViviendaController@index')->name('comprasViviendas');
Route::get('comprasViviendasLujo','ComprasViviendaLujoController@index')->name('comprasViviendasLujo');
Route::get('comprasSolares','ComprasSolaresController@index')->name('comprasSolares');
Route::get('comprasParcelas','ComprasParcelasController@index')->name('comprasParcelas');
Route::get('comprasTerrenos','ComprasTerrenosController@index')->name('comprasTerrenos');

Route::get('alquilerViviendas','AlquilerViviendasController@index')->name('alquilerViviendas');
Route::get('alquilerHabitacionesLujo','AlquilerHabitacionesLujoController@index')->name('alquilerHabitacionesLujo');
Route::get('alquilerHabitacionesPlaya','AlquilerHabitacionesPlayaController@index')->name('alquilerHabitacionesPlaya');
Route::get('alquilerHabitacionesRurales','AlquilerHabitacionesRuralesController@index')->name('alquilerHabitacionesRurales');

Route::get('contacto','ContactoController@index')->name('contacto');

Route::get('perfil','PerfilController@index')->name('perfil');
Route::get('perfilVendedor','PerfilVendedorController@index')->name('perfilVendedor');
Route::get('perfilComprador','PerfilCompradorController@index')->name('perfilComprador');


Route::get('mensajes','CMensajesController@index')->name('mensajes');
route::resource('mensajes', 'CMensajesController');



Route::get('inmuebles','InmueblesController@index')->name('inmuebles');
route::resource('inmuebles','InmueblesController');


Route::get('usuarios','usuariosController@index')->name('usuarios');
route::resource('usuarios','UsuariosController');
route::resource ('/usuarios','UsuariosController');

Route::get('anunciosVendedor','AnunciosVendedorController@index')->name('anunciosVendedor');
Route::resource('anunciosVendedor','AnunciosVendedorController');


Route::get('anunciosAdministrador','AnunciosAdministradorController@index')->name('anunciosAdministrador');
Route::resource('anunciosAdministrador','AnunciosAdministradorController');

Route::resource('/vendedor', VendedorController::class);
Route::resource('/comprador', CompradorController::class);

resources/views/alquilerHabitacionesLujo.blade.php
@extends('template2')
@section('Container')
<div class="container">
        <div class="row">
          <div class="col l12 m8 s12">
           <h5>   <p class="blue-grey-text text-darken-3 ">Vivienda lujo
              <input type="searchp">
              <a class="btn-floating btn-small waves-effect waves-light blue-grey darken-3 "><i class="material-icons">search</i></a>
            </div>
        </p> </h5>
          </h1>
        </div>
      </div>

<div class="container">
    <div class="row">
         <!-- Card 1 -->
        <div class="col l6 s12 m8">
          <div class="card">
            <div class="card-image">
                <img src="img/viviendalujo1.jpg" alt="" width="100" height="350">
        <span class="card-title">Villa / Chalet de 2800 m2</span>
      </div>
      <div class="card-content">
        <p aling="justify">
            Fecha de publicación: 27/06/2020 <br>
            Dirección: zona residencial de Madrid: La Moraleja<br>
            Precio: x <br>
            Descripción: Cuenta con 11 recamaras con baño personal, Gimnasio con vistas al jardín,Spa con piscina de 60 m2,
            Salón cinema con unos 100 m2 ,Garaje, etc. <br>
          </p>
            </div>
            <div class="card-action">
                <p align="right">Contactar al vendedor
                    <a class="btn-floating btn-Large waves-effect waves-light  blue-grey darken-3 pull-right align=right btn modal-trigger" href="#modal1" > <i class="material-icons">chat</i>Iniciar Chat </a>
                  </p>
            </div>
          </div>
        </div>
        <!-- Card 2 -->
        <div class="col l6 s12 m8">
            <div class="card">
              <div class="card-image">
                <img src="img/viviendalujo2.jpg" alt="" width="100" height="350">
                <span class="card-title ">Madrid España</span>
              </div>
              <div class="card-content">
                <p aling="justify">
                  Fecha de publicación: 21/08/2021 <br>
                  Dirección: zona de seguridad de Las Encinas <br>
                  Precio: x <br>
                  Descripción: 15.000m2 de parcela, bordeando la reserva natural, vestidor, salón privado, 
                  La suite principal tiene un gran vestidor y baño etc. <br>
                </p>
              </div>
              <div class="card-action">
                  <p align="right">Contactar al vendedor
                      <a class="btn-floating btn-Large waves-effect waves-light  blue-grey darken-3 pull-right align=right btn modal-trigger" href="#modal1" > <i class="material-icons">chat</i>Iniciar Chat </a>
                    </p>
              </div>
            </div>
          </div>
      <!-- Card 3 -->
      <div class="col l6 s12 m8">
        <div class="card">
          <div class="card-image">
            <img src="img/viviendalujo3.jpg" alt="" width="100" height="350">
            <span class="card-title">Chalet de lujo de 1173 m2 </span>
          </div>
          <div class="card-content">
            <p aling="justify">
              Fecha de publicación: 7/09/2021 <br>
              Dirección:  zona de Valdemarin <br>
              Precio: x <br>
              Descripción: Cuenta comedor, salón TV, cocina, aseo de cortesía, despacho, cuarto de juegos, 
              habitación de invitados con su baño completo, etc. <br>
      
            </p>
          </div>
          <div class="card-action">
              <p align="right">Contactar al vendedor
                  <a class="btn-floating btn-Large waves-effect waves-light  blue-grey darken-3 pull-right align=right btn modal-trigger" href="#modal1" > <i class="material-icons">chat</i>Iniciar Chat </a>
                </p>
          </div>
        </div>
      </div>
      <!-- Card 4 -->
      <div class="col l6 s12 m8">
        <div class="card">
          <div class="card-image">
            <img src="img/viviendalujo4..jpg" alt="" width="100" height="350">
            <span class="card-title">Casa adosada de lujo de 626 m2</span>
          </div>
          <div class="card-content">
            <p aling="justify">
              Fecha de publicación: 10/05/2021 <br>
              Dirección: LA FINCA Pº de los Lagos 2, Madrid <br>
              Precio: x <br>
              Descripción: Cuenta Amplia cocina con office y aseo de cortesía,salón-comedor de 95m2 con acceso al jardín y piscina privada  
              Sótano: Con luz natural y ventilación, etc. <br>
            </p>
          </div>
          <div class="card-action">
              <p align="right">Contactar al vendedor
                  <a class="btn-floating btn-Large waves-effect waves-light  blue-grey darken-3 pull-right align=right btn modal-trigger" href="#modal1" > <i class="material-icons">chat</i>Iniciar Chat </a>
                </p>
          </div>
        </div>
      </div>
</div>
 
<!-- Modales -->
<!-- Modal Structure -->
<div id="modal1" class="modal grey lighten-2">

<div class="container">
    <div class="row valign-wrapper">
        <div class="col l12 s6 m8 ">
            <div class="row white">
                <h5 class="grey darken-3 white-text center card-panel">Contactar al vendedor</h5>
                <form action="{{route('mensajes.store')}}" method="POST">
    @csrf
                    <div class="row">
                        <div class="col l12 s12 input-field">
                          <i class="material-icons prefix">perm_identity</i>
                          <input class="form-control @error('email') is-invalid @enderror" value="{{ old('email') }}"
                           required autocomplete="email" autofocus
                           type="email" name="email" id="email" required>
                          <label for="email">Email</label>
                          @error('email')
                          <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                         @enderror
                        </div>
                      </div>
                      <div class="row">
                        <div class="col l12 s12 input-field">
                            <i class="material-icons prefix">perm_identity</i>
                            <input class="form-control @error('name') is-invalid @enderror" value=" {{ Auth::user()->name }}"
                               required autocomplete="name" autofocus
                               type="text" name="user_name" id="name" required>
                              <label for="name">Nombre</label>
                              @error('name')
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $message }}</strong>
                              </span>
                             @enderror
                        </div>
                      </div>
                        <div class="row">
                            <div class="col l12  s12 input-field">
                                <i class="material-icons prefix">description</i>
                                <input class="form-control validate" value=""
                                   required autocomplete="descripcion" autofocus
                                   type="text" name="descripcion" id="descripcion" required>
                                  <label for="descripcion">Descripcion</label>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col l12  s12 input-field">
                                <i class="material-icons prefix">description</i>
                                <input class="form-control validate" value="Alquiler Habitacion lujo"
                                   required autocomplete="asunto" autofocus
                                   type="text" name="asunto" id="asunto" required>
                                  <label for="asunto">Asunto</label>
                            </div>
                        </div>
                        <div class="row right">
                            <div class="col l12 s12">
                                <button class="  btn  grey darken-3 btn-dannger waves-effect waves-light btn" type="submit"><i class="material-icons right">send</i>
                                    ENVIAR
                                    </button>
                            </div>
                            
                          </div> 
                        </div>
                    </div> 
                   </form>
            </div>
        </div>
       </div>
</div>  
</div>
@endsection

resources/views/alquilerHabitacionesRurales.blade.php
@extends('template2')
@section('Container')
 
  <!-- busqueda-->

  <div class="container">
    <div class="row">
      <div class="col l12 m8 s12">
       <h5>   <p class="light- brown-text  text-darken-3 "> Habitacion Rural
          <input type="searchp">
          <a class="btn-floating btn-small waves-effect waves-light  brown"><i class="material-icons">search</i></a>
        </div>
    </p> </h5>
</h1>
    </div>
  </div>


  <div class="container">
    <div class="row">
         <!-- Card 1 -->
        <div class="col l6 s12 m8">
          <div class="card">
            <div class="card-image">
              <img src="img/habitacionr1.jpg" alt="" width="100" height="250">
              <span class="card-title">inmueble Jalos</span>
            </div>
            <div class="card-content">
              <p aling="justify">
                Fecha de publicación: 25/05/2020 <br>
                Dirección: Av. Valle escondido #30 <br>
                Precio: $4500.00 <br>
                Descripción: Cuenta con 2 recamaras con baño personal, cocina, comedor, patio,cochera y sala.
               <br><br>
              </p>
            </div>
            <div class="card-action">
                <p align="right">Contactar al vendedor
                    <a class="btn-floating btn-Large waves-effect waves-light   brown pull-right align=right btn modal-trigger" href="#modal1" > <i class="material-icons">chat</i>Iniciar Chat </a>
                  </p>
            </div>
          </div>
        </div>
        <!-- Card 2 -->
        <div class="col l6 s12 m8">
            <div class="card">
              <div class="card-image">
                <img src="img/habitacionr2.jpg" alt="" width="100" height="250">
                <span class="card-title">inmueble santa Maria</span>
              </div>
              <div class="card-content">
                <p aling="justify">
                  Fecha de publicación: 28/08/2021 <br>
                  Dirección: Av. Santa Maria #8 <br>
                 
                  Precio: $1500.00 <br>
                 
                  Descripción: Cuenta con 2 recamaras, 3 baños cocina, comedor, patio, alberca, cochera, sala,
                  lavandería, área de entretenimiento, etc. <br>
                </p>
              </div>
              <div class="card-action">
                  <p align="right">Contactar al vendedor
                      <a class="btn-floating btn-Large waves-effect waves-light   brown pull-right align=right btn modal-trigger" href="#modal1" > <i class="material-icons">chat</i>Iniciar Chat </a>
                    </p>
              </div>
            </div>
          </div>
      <!-- Card 3 -->
      <div class="col l6 s12 m8">
        <div class="card">
          <div class="card-image">
            <img src="img/habitacionr3.jpg" alt=""width="100" height="250">
            <span class="card-title">inmueble Michoacan</span>
          </div>
          <div class="card-content">
            <p aling="justify">
              Fecha de publicación: 06/04/2021 <br>
              Dirección: Av. 5 de mayo #18 <br>
              Precio: $1500.00 <br>
              Descripción: Cuenta con 1 recamara  con baño personal, cocina, comedor, patio,cochera y sala
             <br><br>
            </p>
          </div>
          <div class="card-action">
              <p align="right">Contactar al vendedor
                  <a class="btn-floating btn-Large waves-effect waves-light   brown pull-right align=right btn modal-trigger" href="#modal1" > <i class="material-icons">chat</i>Iniciar Chat </a>
                </p>
          </div>
        </div>
      </div>
      <!-- Card 4 -->
      <div class="col l6 s12 m8">
        <div class="card">
          <div class="card-image">
            <img src="img/habitacionr4.jpg" alt="" width="100" height="250">
          <span class="card-title">inmueble  Veracruz</span>
        </div>
        <div class="card-content">
          <p aling="justify">
            Fecha de publicación: 15/12/2020 <br>
            Dirección: Av. luis Jasso #9 <br>
            Precio: $2500.00 <br>
            Descripción: Cuenta con 3 recamaras  con baño personal, cocina, comedor, patio,cochera , gimanasio y sala
           <br><br>
          </p>
          </div>
          <div class="card-action">
              <p align="right">Contactar al vendedor
                  <a class="btn-floating btn-Large waves-effect waves-light   brown pull-right align=right btn modal-trigger" href="#modal1" > <i class="material-icons">chat</i>Iniciar Chat </a>
                </p>
          </div>
        </div>
      </div>
</div>
 
<!-- Modales -->
<!-- Modal Structure -->
<div id="modal1" class="modal grey lighten-2">

<div class="container">
    <div class="row valign-wrapper">
        <div class="col l12 s6 m8 ">
            <div class="row white">
                <h5 class="grey darken-3 white-text center card-panel">Contactar al vendedor</h5>
                <form action="{{route('mensajes.store')}}" method="POST">
    @csrf
                    <div class="row">
                        <div class="col l12 s12 input-field">
                          <i class="material-icons prefix">perm_identity</i>
                          <input class="form-control @error('email') is-invalid @enderror" value="{{ old('email') }}"
                           required autocomplete="email" autofocus
                           type="email" name="email" id="email" required>
                          <label for="email">Email</label>
                          @error('email')
                          <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                         @enderror
                        </div>
                      </div>
                      <div class="row">
                        <div class="col l12 s12 input-field">
                            <i class="material-icons prefix">perm_identity</i>
                            <input class="form-control @error('name') is-invalid @enderror" value=" {{ Auth::user()->name }}"
                               required autocomplete="name" autofocus
                               type="text" name="user_name" id="name" required>
                              <label for="name">Nombre</label>
                              @error('name')
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $message }}</strong>
                              </span>
                             @enderror
                        </div>
                      </div>
                        <div class="row">
                            <div class="col l12  s12 input-field">
                                <i class="material-icons prefix">description</i>
                                <input class="form-control validate" value=""
                                   required autocomplete="descripcion" autofocus
                                   type="text" name="descripcion" id="descripcion" required>
                                  <label for="descripcion">Descripcion</label>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col l12  s12 input-field">
                                <i class="material-icons prefix">description</i>
                                <input class="form-control validate" value="Alquiler Habitacion rural"
                                   required autocomplete="asunto" autofocus
                                   type="text" name="asunto" id="asunto" required>
                                  <label for="asunto">Asunto</label>
                            </div>
                        </div>
                        <div class="row right">
                            <div class="col l12 s12">
                                <button class="  btn  grey darken-3 btn-dannger waves-effect waves-light btn" type="submit"><i class="material-icons right">send</i>
                                    ENVIAR
                                    </button>
                            </div>
                            
                          </div> 
                        </div>
                    </div> 
                   </form>
            </div>
        </div>
       </div>
</div>  
</div>
@endsection

resources/views/anunciosAdministrador.blade.php
@extends('template3')
@section('Container')
<div class="container">
<h4 class="grey-text center">ANUNCIOS REALIZADOS POR USUARIOS</h4>
</div>
<div class="container">
<table class="table table-bordered">
<thead class="grey darken-2 white-text">
<tr>
<th class="center">ID</th>
<th class="center">NOMBRE COMPLETO</th>
<th class="center">TIPO DE INMUEBLE</th>
<th class="center">DIRECCIÓN</th>
<th class="center">PRECIO</th>
<th class="center">DESCRIPCIÓN</th>
<th class="center">FECHA DE PUBLICACIÓN</th>
<th class="center">Eliminar</th>
</tr>
</thead>
<tbody class="white">
@foreach($anunciosAdministrador as $anuncio)
<tr class="black-text center">
<td>{{$anuncio->id}}</td>
<td>{{$anuncio->name}}</td>
<td>{{$anuncio->tipo}}</td>
<td>{{$anuncio->direccion}}</td>
<td>{{$anuncio->precio}}</td>
<td>{{$anuncio->descripcion}}</td>
<td>{{$anuncio->created_at}}</td>
<td><a href="#borrar"  class="waves-effect waves-light btn red modal-trigger">
<i class="material-icons center">delete</i></a></td>
</tr>
@endforeach
</tbody>
</table>
<br>
<br>
<br>
<br>
<br>
<br>
</div>
<div id="borrar" class="modal">
  <div class="modal-content">
  <h5 class="grey darken-3 white-text center card-panel">¿Estas seguro de eliminar este anuncio?</h5>  </div>
  <center>
  <h5>  Una vez borrado el anuncio, no podra deshacer los cambios</h5>
  </center>
  <br>
    <div class="modal-footer">
      <div class="row right-align">
      <form action="{{url('/anunciosVendedor/'.$anuncio->id)}}" method="POST" class="d-nline-block">
        {{method_field('DELETE')}}
          @csrf
          <center>
          <button class="btn waves-effect waves-light green" type="submit" name="action">Aceptar</button>
        <a class="btn red modal-close">Cancelar</a>
          </center>
      
      </form> 
      </div>   
   </div>
</div>
@endsection

resources/views/anunciosVendedor.blade.php
@extends('template4')

@section('Container')
<div class="container">
            <div class="row valign-wrapper">
              <div class="col s6 offset-s3 valign">
                  <div class="row white">
                      <h5 class="grey darken-3 white-text center card-panel">Registro de anuncios</h5>
                      <form method="POST" action="{{ route('anunciosVendedor.store') }}">
                          @csrf
                          <div class="row">
                              <div class="col l12 s12 input-field">
                                  <i class="material-icons prefix">perm_identity</i>
                                  <input class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}"
                                     required autocomplete="name" autofocus
                                     type="text" name="name" id="name" required>
                                    <label for="name">Nombre completo</label>
                              </div>
                          </div>
                          <div class="row">
                            <div class="col l12 s12 input-field">
                            <i class="material-icons prefix">home</i>
                            <select name="tipo" id="tipos">
                                 @foreach($inmuebles as $inmueble )
                                     <option>{{$inmueble->tipo}}  {{$inmueble->descripcion}}</option>
          
                                 @endforeach
                             </select>
                            </div>
                          </div>
                          <div class="row">
                              <div class="col l12 s12 input-field">
                                  <i class="material-icons prefix">directions</i>
                                  <input class="form-control" value="{{ old('direccion') }}"
                                     required 
                                     type="text" name="direccion" id="direccion" required>
                                    <label for="direccion">Direccion</label>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col l12 s12 input-field">
                                  <i class="material-icons prefix">attach_money</i>
                                  <input class="form-control" value="{{ old('precio') }}"
                                     required 
                                     type="text" name="precio" id="precio" required>
                                    <label for="precio">Precio</label>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col l12 s12 input-field">
                                  <i class="material-icons prefix">book</i>
                                  <input class="form-control" value="{{ old('descripcion') }}"
                                     required 
                                     type="text" name="descripcion" id="descripcion" required>
                                    <label for="descripcion">Descripcion</label>
                              </div>
                          </div>
                       
                          
                  
                            <div class="row center">
                              <button class=" green waves-effect waves-light btn" 
                              type="submit"><i class="material-icons right">send</i>
                              Anunciar
                              </button>
                              <button class=" red waves-effect waves-light btn" 
                              ><i class="material-icons right">cancel</i>
                              Cancelar
                              </button>
                            </div>
                      </form>
                  </div>
              </div>
            </div>
          </div> 
@endsection

resources/views/comprador.blade.php
@extends('template2')
@section('Container')
<div class="container">
  <div class="row">
    <div class="col l12 m8 s12">
    <h1 class=" center light-blue-text  text-darken-3">Viventa</h1>
    </div>
  </div>
  <div>
    <p class="center light-blue-text  text-darken-3">Encuentra aqui tu hogar </p>
  </div>
  <div class="video-container">
    <iframe width="560" height="315"
      src="https://www.youtube.com/embed/dmh8JExsNt4" title="YouTube video player" 
      frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
      allowfullscreen>
    </iframe>
  </div>
</div>
<br>
@endsection

resources/views/home.blade.php
@extends('template3')

@section('Container')
    <div class="container">
  <div class="row">
    <div class="col l12 m8 s12">
    <h1 class=" center light-blue-text  text-darken-3">Viventa</h1>
    </div>
  </div>
  <div>
    <p class="center light-blue-text  text-darken-3">Encuentra aqui tu hogar </p>
  </div>
  <div class="video-container">
    <iframe width="560" height="315"
      src="https://www.youtube.com/embed/dmh8JExsNt4" title="YouTube video player" 
      frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
      allowfullscreen>
    </iframe>
  </div>
</div>
<br>
@endsection

resources/views/perfilVendedor.blade.php
@extends('template4')
@section('Container')
<div class="row">
      <div class="col l1 s12">
      </div>
      <div class="col l4 s12">
          <br><br>
        <div class="card z-depth-5">
          <div class="card-image grey darken-1">
            <img src="img/perfil.jpg" alt="">
            <span class="card-title">perfil</span>
          </div>
          <div class="card-action">
              <p align="right">
            <a href="#" class="blue-text">Cambiar foto de perfil</a></p>
          </div>
        </div>
      </div>
      <div class="col l6 s12">
        <div class="card z-depth-5">
          <div class="card-content">
          <form action="" method="POST">
          <label for="nombre">Nombre</label>
          <input type="text" name="nombre" id="nombre" value="{{ Auth::user()->name }}" required> 

          <label for="apellidos">Apellidos</label>
          <input type="text" name="apellidos" id="apellidos" value="{{ Auth::user()->apellidos }}" required>
         
          <label for="tipo">Tipo de usuario</label>
          <input type="text" name="tipo" id="tipo" value="{{ Auth::user()->tipo }}" required> 
         
          <label for="Contrasenia">Contraseña</label>
          <input type="password" name="password" id="password" value="{{ Auth::user()->password }}"required>
          
          <label for="email">e-mail</label>
          <input type="email" name="email" id="email" value="{{ Auth::user()->email }}"required>
          </div>
          <div class="card-action">
          <p align="right">
            <a href="#" class="blue-text">Actualizar mis datos</a> </p>
          </div>
          </form>
        </div>
      </div>
      <div class="col l1 s12">
      </div>
</div>
@endsection